explicitly say how to migrate to nginx
openmicroscopy/ome-documentation pull request #1579
Opened 2016-11-29 09:57 UTC by aleksandra-tarkowska

This PR should clarify that `application_server` must be set to wsgi-tcp. I imaging if people migrate from apache to nginx this may be missing and cause more community questions about:

```
    Cannot configure omero web to use nginx:
    Error running bin/omero  web config nginx - I get the error
    Configuration mismatch omero.web.application_server=wsgi cannot be used with omero web config nginx.
```

2016-11-29 10:02 UTC, hflynn requested changes
Spelling error and a style nitpick to fix

2016-11-29 10:02 UTC, hflynn commented on omero/sysadmins/server-upgrade.txt
> +It is recomanded using :doc:`install-nginx` or
recomanded -> recommended

2016-11-29 10:02 UTC, hflynn commented on omero/sysadmins/troubleshooting.txt
> +It is recomanded using :doc:`install-nginx` or
recomanded -> recommended

2016-11-29 10:02 UTC, hflynn commented on omero/sysadmins/unix/install-web/install-nginx.txt
> +Set the following:
you can put `::` after 'following' here so you only need one blank line before '$bin/omero...'

2016-11-29 10:02 UTC, hflynn commented on omero/sysadmins/unix/install-web/install-web-trial.txt
> +Set the following:
As above, you can put the double :: here and move the code extract up to line 91

2016-11-29 10:16 UTC, hflynn commented on omero/sysadmins/server-upgrade.txt
> +It is recommended using :doc:`install-nginx` or
This doc link is breaking the build too I'm afraid, you need to file path

2016-11-29 10:59 UTC, hflynn commented
Built on staging now - https://www.openmicroscopy.org/site/support/omero5.3-staging/sysadmins/server-upgrade.html#omero-web-migrating-from-apache-to-nginx, https://www.openmicroscopy.org/site/support/omero5.3-staging/sysadmins/troubleshooting.html#troubleshooting-omeroweb-migrate-to-nginx etc - looks fine but will list for technical review tomorrow before merging and rebasing to dev_5_2.

2016-11-29 10:59 UTC, hflynn approved these changes

2016-11-30 08:26 UTC, mtbc commented on omero/sysadmins/server-upgrade.txt
> +It is recommended using :doc:`/sysadmins/unix/install-web/install-nginx` or
"It is recommending using ..." reads weirdly to me. "It is recommended to use ..." or "We recommend using ..." perhaps?

2016-11-30 08:27 UTC, mtbc commented on omero/sysadmins/troubleshooting.txt
> +    $bin/omero config set omero.web.application_server "wsgi-tcp"
a space after the `$`?

2016-11-30 11:47 UTC, jburel commented
using 5.3.0-m5 server on ubuntu 14.04
 * run ``OMERO.server/bin/omero config set omero.web.application_server wsgi``
 * if we try to start web w/o any other configuration, it falls back to "apache" and we have the following message
``
609 static files copied to '/home/omero/OMERO.server/lib/python/omeroweb/static', 2 post-processed.
Clearing expired sessions. This may take some time... [OK]
[ERROR] You are deploying OMERO.web using Apache and mod_wsgi. OMERO.web does not provide any management for the daemon process which communicates with Apache child processes using UNIX sockets to handle a request.
Generate apache config using 'omero web config apache' or 'omero web config apache24' and reload web server.
``
 * if the following command is run:
``OMERO.server/bin/omero web config nginx --http 80 > OMERO.server/nginx.conf.tmp``
The expected error message is displayed
``configuration mismatch. omero.web.application_server=wsgi cannot be used with 'omero web config nginx'.``

* Change ``wsi`` to ``wsi-tcp``. Web restart w/o error
* unset  `` omero.web.application_server`` and restarted web

2016-11-30 13:40 UTC, hflynn commented
Possible rebase candidate for 5.2.7 release

2016-12-08 06:52 UTC, jburel commented on omero/sysadmins/unix/install-web/install-nginx.txt
> +    $bin/omero config set omero.web.application_server "wsgi-tcp"
space ``$ bin/omero``

2016-12-08 06:52 UTC, jburel commented on omero/sysadmins/unix/install-web/install-web-trial.txt
> +    $bin/omero config set omero.web.application_server "wsgi-tcp"
space ``$ bin/omero``

2016-12-08 06:53 UTC, jburel commented
@aleksandra-tarkowska: 2 minor changes then we can rebase it and I will start a new 5.2 build

2016-12-08 08:14 UTC, mtbc commented
Maybe also look at https://github.com/openmicroscopy/ome-documentation/pull/1579#discussion_r90186628 ?  Though if it reads okay to @hflynn then I'm fine with it.

2016-12-08 10:04 UTC, aleksandra-tarkowska commented on omero/sysadmins/troubleshooting.txt
> +It is recommended to use :doc:`/sysadmins/unix/install-web/install-nginx` or
@mtbc  I changed that somewhere else :)

2016-12-08 10:10 UTC, jburel commented
Looks good thanks @aleksandra-tarkowska 
Could you rebase it to 5.2?

2016-12-08 10:15 UTC, aleksandra-tarkowska commented
--rebased-to #1588

2016-12-12 11:09 UTC, hflynn commented
Merging as this is now on the 5.2 branch anyway. We can always do some minor wording fixes before the 5.3 release.

2016-12-12 11:09 UTC, merged