Instructions for win 5.2 to linux 5.3 migration
openmicroscopy/ome-documentation pull request #1634
Opened 2017-03-03 13:46 UTC by dominikl

This PR just adds a brief summary of how to migrate from a OMERO 5.2 installation on Windows to 5.3.0 on Linux.

2017-03-03 13:47 UTC, dominikl commented on omero/sysadmins/windowsmigration.txt
> +  :doc:`/sysadmins/server-upgrade#upgrade-your-database` documentation
Does anyone know how I can link to an anchor in sphinx syntax? This doesn't work unfortunately.

2017-03-03 13:56 UTC, hflynn commented on omero/sysadmins/windowsmigration.txt
> +  :doc:`/sysadmins/server-upgrade#upgrade-your-database` documentation
Ah, you found it I see :)

2017-03-03 13:58 UTC, dominikl commented on omero/sysadmins/windowsmigration.txt
> +  :doc:`/sysadmins/server-upgrade#upgrade-your-database` documentation
Yes, @sbesson pointed me to an example, thanks.

2017-03-03 13:58 UTC, hflynn commented
You'll need to add your new page to a TOC on the index page so the build knows where it lives in the browsing order.

2017-03-03 14:02 UTC, hflynn commented
I'd add it to the 'Server Maintenance and Upgrading' section

2017-03-03 14:22 UTC, hflynn commented on omero/sysadmins/windowsmigration.txt
> +part (setting the OMERO binary repository location)
No full stop at the end of the sentence.

2017-03-03 14:23 UTC, hflynn commented on omero/sysadmins/windowsmigration.txt
> +server installation
Missing full stop here too

2017-03-03 14:23 UTC, hflynn commented
Staged at https://www.openmicroscopy.org/site/support/omero5.3-staging/sysadmins/windowsmigration.html

2017-03-03 14:25 UTC, hflynn commented on omero/sysadmins/windowsmigration.txt
> +::
You can put these `::` markers at the end of your previous text so you don't need all these extra lines

2017-03-03 14:26 UTC, hflynn commented on omero/sysadmins/windowsmigration.txt
> +  to the Linux system (e.g. /OMERO).
These last two points have full stops after them but the rest don't

2017-03-03 14:29 UTC, hflynn commented on omero/sysadmins/windowsmigration.txt
> +::
Also so you can indent the code blocks to fit inline below the bullet points

2017-03-03 14:30 UTC, hflynn commented
A few minor style nitpicks but otherwise renders fine on staging

2017-03-03 15:02 UTC, mtbc commented on omero/sysadmins/whatsnew.txt
> +- Windows support discontinued, see :doc:`/sysadmins/windowsmigration`
end with period ?

2017-03-03 15:03 UTC, mtbc commented on omero/sysadmins/windowsmigration.txt
> +- Create a dump of the OMERO SQL database, either using PGAdmin or the pg_dump
guess we have some useful markup for commands like `pg_dump`

2017-03-03 15:03 UTC, mtbc commented on omero/sysadmins/windowsmigration.txt
> +- Backup the OMERO data directory (e.g. C:\\OMERO ).
probably have `:file:` markup for paths

2017-03-03 15:06 UTC, mtbc commented on omero/sysadmins/windowsmigration.txt
> +  e. g. using psql command line::
some kind of command markup for `psql`

2017-03-03 15:07 UTC, mtbc commented on omero/sysadmins/windowsmigration.txt
> +Finally startup the OMERO server and check the log files for errors.
"start up" or, maybe better, just "start"

2017-03-06 10:14 UTC, joshmoore requested changes
Looks generally good. Mostly minor suggestions, but there is some risk of a user multiply copying data when not necessary. A sentence or two about the overall goals of each step _might_ help.

2017-03-06 10:14 UTC, joshmoore commented on omero/sysadmins/windowsmigration.txt
> +- Backup the OMERO data directory (e.g. :file:`C:\\OMERO`).
The point to get across is that they *must* maintain a pristine copy of the original system if they want us to help them find errors later. *If* they are going to just leave the Windows data where it is (and for example rsync it over), then at this point they don't need to do anything. But if they are using NFS or something, then at this point they should make another copy for later.

2017-03-06 10:14 UTC, joshmoore commented on omero/sysadmins/windowsmigration.txt
> +  program.
Perhaps give the command here (` sudo -u postgres pg_dump ...`) which will match the command below or in general refer to the backup/restore page.

2017-03-06 10:41 UTC, hflynn commented
@dominikl while you are making some more changes anyway, can you rename your new file 'windows-migration' with a dash to match most of the other filenames for consistency please? (Yes, I realise they aren't all matching currently but still)

2017-03-07 12:05 UTC, joshmoore requested changes
Few more minor comments but the general "maintain a pristine copy" is now quite clear. Thanks!

2017-03-07 12:05 UTC, joshmoore commented on omero/sysadmins/windows-migration.txt
> +- Please keep a pristine copy of your Windows OMERO server, until you are
"binary repository" is the term used under backup and restore:

```
omero/sysadmins/server-backup-and-restore.txt:store <unix/server-binary-repository>`. The entire contents of ``/OMERO`` should be
```

Perhaps the same link could be used?

2017-03-07 12:05 UTC, joshmoore commented on omero/sysadmins/windows-migration.txt
> +- See also :doc:`/sysadmins/server-backup-and-restore`.
"For more details on the standard backup procedure, see..."

2017-03-07 12:05 UTC, joshmoore commented on omero/sysadmins/windows-migration.txt
> +    omero config set ...
backup-and-restore suggests: `load`.

2017-03-08 08:12 UTC, joshmoore approved these changes

2017-03-08 09:36 UTC, merged