Web doc
openmicroscopy/ome-documentation pull request #1671
Opened 2017-03-30 19:11 UTC by jburel

Review the web section from the general installation page

See https://trello.com/c/XH0xqUIt/60-installation-page-clarification

2017-04-05 09:23 UTC, hflynn requested changes
A few style nitpicks

2017-04-05 09:23 UTC, hflynn commented on omero/sysadmins/unix/server-centos6-ice36.txt
> +Installing and Running OMERO.web
should be 'running' - only the first word of the subtitles has a capital letter

2017-04-05 09:23 UTC, hflynn commented on omero/sysadmins/unix/server-centos7-ice36.txt
> +Installing and Running OMERO.web
Same comment as above

2017-04-05 09:23 UTC, hflynn commented on omero/sysadmins/unix/server-centos7-ice36.txt
> +
unneeded extra whitespace

2017-04-05 09:23 UTC, hflynn commented on omero/sysadmins/unix/server-centos6-ice36.txt
>  Running OMERO
Having 'Running OMERO' right underneath '...Running OMERO.web' is slightly confusing, maybe this would be better as 'Running OMERO.server'?

2017-04-05 09:23 UTC, hflynn commented on omero/sysadmins/unix/server-centos7-ice36.txt
>  Running OMERO
Again, maybe 'Running OMERO.server' to be less confusing with '..Running OMERO.web' above

2017-04-05 09:23 UTC, hflynn commented on omero/sysadmins/unix/server-ubuntu-ice36.txt
> +Installing and Running OMERO.web
'Running' -> 'running' as above

2017-04-05 12:11 UTC, will-moore commented on omero/sysadmins/unix/server-centos6-ice36.txt
> +--------------------------------
Under 'running OMERO.web' I don't see ```bin/omero web start``` anywhere?

2017-04-05 12:16 UTC, will-moore commented on omero/sysadmins/unix/server-ubuntu-ice36.txt
> +--------------------------------
Same: bin/omero web start?

2017-04-05 12:20 UTC, jburel commented on omero/sysadmins/unix/server-centos6-ice36.txt
> +--------------------------------
This is correct since it depends on how you have installed it So only have the link to the web installation walkthrough

2017-04-06 08:40 UTC, hflynn approved these changes

2017-04-17 14:23 UTC, merged