open_with update warning
openmicroscopy/ome-documentation pull request #1699
Opened 2017-06-15 14:02 UTC by will-moore

See discussion at https://github.com/openmicroscopy/openmicroscopy/pull/5317/
This PR describes the problem with previously-configured open_with overriding the new 'Image Viewer' config and links to the PR above for how to manually update.

cc @jburel.

2017-06-15 14:13 UTC, jburel commented on omero/sysadmins/server-upgrade.txt
> +you wish to have the old ``webgateway`` viewer available via ``Open with > Image Viewer``
maybe remove old

2017-06-15 15:31 UTC, mtbc commented on omero/sysadmins/server-upgrade.txt
> +will then be stored in /etc/grid.xml.
`:file:` markup -- and really in the top-level `/etc/` ?

2017-06-16 07:09 UTC, joshmoore commented
Would a table of example help here? e.g. "If you did X in version Y, then now do Z..."

2017-06-16 08:23 UTC, will-moore commented on omero/sysadmins/server-upgrade.txt
> +will then be stored in /etc/grid.xml.
In the ```OMERO-SERVER/etc/grid.xml``` unless I've got that completely wrong? I just assumed the "omero-server" bit wasn't needed, but I'll add it...

2017-06-16 08:25 UTC, mtbc commented on omero/sysadmins/server-upgrade.txt
> +will then be stored in /etc/grid.xml.
`etc/grid.xml` would be fine but `/etc/grid.xml` does suggest it starts at the top of the filesystem.

2017-06-16 08:27 UTC, will-moore commented on omero/sysadmins/server-upgrade.txt
> +you wish to have the old ``webgateway`` viewer available via ``Open with > Image Viewer``
I just wanted to convey that this wasn't something new (I don't think users will recognise the "webgateway" name). Maybe "existing" or "standard" or "regular"? (don't want "default" as I've used that term elsewhere to refer to configs).

2017-06-16 08:54 UTC, manics commented on omero/sysadmins/server-upgrade.txt
> +will then be stored in /etc/grid.xml.
Shouldn't it be `etc/grid/config.xml`?

2017-06-16 10:16 UTC, jburel commented on omero/sysadmins/server-upgrade.txt
> +you wish to have the old ``webgateway`` viewer available via ``Open with > Image Viewer``
existing will be better

2017-06-20 11:11 UTC, will-moore commented
@joshmoore I'm all for improving clarity but I'm not sure a table would help (unless I'm not quite understanding you)? There's only a single case where you do need to do the manual update, so I'd prefer not to add a matrix of all the other cases where you don't need to.

2017-06-20 11:50 UTC, joshmoore commented
Fair enough, but here's a heads up that I found the prose here confusing. Perhaps at least an example of before/after. If we've essentially broken a production configuration value, we should be take care to make sure it's clear.

2017-06-20 13:50 UTC, hflynn commented
I find this text very confusing too. 

I'm also not sure we want to start a precedent of linking to PRs for instructions rather than just further reading if people are particularly interested in the nuts and bolts.

2017-06-20 14:03 UTC, will-moore commented on omero/sysadmins/server-upgrade.txt
> +you wish to have the old ``webgateway`` viewer available via ``Open with > Image Viewer``
On second thoughts, I'll simply remove "old" to keep the text simpler.

2017-06-20 14:18 UTC, will-moore commented
I have tried to simplify the text a little.
I could make the issue clearer by describing a lot more about ```open_with``` config and the ```viewer.view``` config and how settings are saved to ```etc/grid/config.xml``` and the issues we have with updating single items in the lists (as mentioned on the PR) as well as the fix itself?
However, I was trying not to make this too bloated since it is an edge case and won't apply to most users. I'm hoping that most users will simply read the "If.... " statement and understand that they don't need to do anything.
I'm happy to have suggestions on how to make the text clearer, but "it's confusing" is not so helpful as I've already tried to make it as clear as I can.

2017-06-20 14:54 UTC, will-moore commented
As discussed with @hflynn: Move the 'if' statement first, remove the background logic mentioning ```config.xml``` and mention iviewer as example because that's the only case where we've told users to config both webclient.view and open_with.

2017-06-20 15:38 UTC, hflynn commented
👍 I think this is clearer

2017-06-20 19:30 UTC, mtbc commented on omero/sysadmins/server-upgrade.txt
> +then you will find that ``Open with > Image Viewer`` also opens the OMERO.iviewer
I think our markup for this is,
```rst
:menuselection:`Open with --> Image Viewer`
```

2017-06-21 07:27 UTC, joshmoore requested changes

2017-06-21 07:27 UTC, joshmoore commented on omero/sysadmins/server-upgrade.txt
> +`described on this PR <https://github.com/openmicroscopy/openmicroscopy/pull/5317/>`_.
I'd strongly suggest that the example be put here in this page and not require users to go to the PR. We should be the ones to go the extra step, not the users. For comparison, I don't see any other mention of a PR in this repo:

```
$ git grep -E "github.*pull" -- .
common/_ext/edit_on_github.py:Loosely based on https://github.com/astropy/astropy/pull/347
contributing/using-git.txt:(PRs) <https://github.com/openmicroscopy/openmicroscopy/pulls>`_. These
contributing/using-git.txt:-  `Using Pull Requests <http://help.github.com/articles/using-pull-requests>`_
contributing/using-git.txt:-  `Pull Requests 2.0 <https://github.com/blog/712-pull-requests-2-0>`_
omero/index.txt:.. _Pull Requests: http://help.github.com/articles/using-pull-requests
```

2017-06-21 07:34 UTC, jburel commented on omero/sysadmins/server-upgrade.txt
> +`described on this PR <https://github.com/openmicroscopy/openmicroscopy/pull/5317/>`_.
I agree that having the example is better. PR should not be used for reference

2017-06-23 12:15 UTC, jburel commented
@joshmoore Happy with the last commit?

2017-06-23 12:43 UTC, joshmoore approved these changes

2017-06-23 12:44 UTC, joshmoore commented
Yes, thank you.

2017-06-23 12:45 UTC, merged