Contributing documentation
openmicroscopy/ome-documentation pull request #1719
Opened 2017-07-19 19:39 UTC by sbesson

The main purpose of this PR is to add the CI job allowing to integrate and review the PRs opened against the OME website. The Jekyll page and the layout of the job is also reviewed.

To test this PR, review the new WWW-merge entry.

2017-07-20 09:49 UTC, kennethgillen commented
@sbesson  - according to https://ci.openmicroscopy.org/job/CONTRIBUTING-merge-docs/1125/console this is in the merge build for CONTRIB docs - but I don't see it on http://docs-staging.openmicroscopy.org/contributing/ci-docs.html. 

Am I missing something?

2017-07-20 12:58 UTC, sbesson commented
@kennethgillen this is where the deployment/URL can get tricky. The built documentation including the PRs for review is currently only available from the Jenkins workspace or as an archive of the build. The URL you mentioned points to the same static content as https://docs.openmicroscopy.org but from `ome-web-staging`

2017-07-20 13:38 UTC, kennethgillen commented
Okay, thanks. 👍

2017-07-20 13:58 UTC, kennethgillen commented on contributing/ci-docs.txt
> +		#. |merge| and push the branch to https://github.com/snoopycrimecop/www.openmicroscopy.org/tree/gh-pages
and "pushes" ?

2017-07-20 15:22 UTC, kennethgillen reviewed
[this was supposed to be "request changes", doing below]

2017-07-20 15:24 UTC, kennethgillen requested changes
https://github.com/openmicroscopy/ome-documentation/pull/1719#pullrequestreview-51209245

2017-07-24 10:53 UTC, kennethgillen commented
👍  good to merge.

2017-07-24 10:54 UTC, kennethgillen approved these changes

2017-07-31 14:45 UTC, jburel commented on contributing/ci-docs.txt
> +The following set of jobs are used to review or publish the content of the
typo it should be ``is used`` instead of ``are used``

2017-07-31 14:45 UTC, jburel commented on contributing/ci-docs.txt
> +		#. The GitHub pages deploys the staging website content under http://snoopycrimecop.github.io/www.openmicroscopy.org/
deploy

2017-08-07 14:20 UTC, sbesson commented
@jburel pushed

2017-08-08 19:59 UTC, jburel commented
Looks good merging

2017-08-08 19:59 UTC, merged