Add example for the new nginx-location configuration
openmicroscopy/ome-documentation pull request #1738
Opened 2017-08-23 13:22 UTC by manics

Documentation for the additions in https://github.com/openmicroscopy/openmicroscopy/pull/5381
- https://trello.com/c/M4Y3tUIS/123-nginx-location-needs-documenting

This includes some additional autogen files with sed statements to ensure the path matches that for all other examples. This may need to be reviewed for consistency with https://trello.com/c/ArqTYHvJ/135-improve-omeroweb-installation-wrt-virtualenv

2017-08-24 09:59 UTC, joshmoore commented
Note: reviewing under https://ci.openmicroscopy.org/job/OMERO-DEV-merge-docs/ws/src/omero/_build/html/sysadmins/unix/install-web/web-deployment.html#nginx-configuration

2017-08-24 10:06 UTC, joshmoore requested changes
A few comments, but this generally looks good. Only high-level issue is likely whether or not we want subheaders under `#nginx-configuration`. This likely goes along with the re-org that we discussed this morning and so maybe should follow in another PR.

cc: @hflynn @jburel @sbesson

2017-08-24 10:06 UTC, joshmoore commented on omero/autogen_docs
> +$WORKSPACE/OMERO.server/bin/omero web config nginx-location | sed "s|$WORKSPACE|/home/omero|g" | grep -v '^#' > omero/sysadmins/unix/install-web/nginx-location.conf
Does the output file name need updating? `nginx-omero-location.include` is used below

2017-08-24 10:06 UTC, joshmoore commented on omero/sysadmins/unix/install-web/web-deployment.rst
> -OMERO.web requires ``body_in_file_only`` adjusted in your default nginx
Should `body_in_file_only` not be referenced somewhere?

2017-08-24 10:06 UTC, joshmoore commented on omero/sysadmins/unix/install-web/web-deployment.rst
> +This requires more initial work but in future you can automatically
in _the_ future

2017-08-24 14:29 UTC, manics commented on omero/sysadmins/unix/install-web/web-deployment.rst
> -OMERO.web requires ``body_in_file_only`` adjusted in your default nginx
I removed `body_in_file_only` because I can't find any mention of it.

2017-08-24 14:33 UTC, joshmoore commented on omero/sysadmins/unix/install-web/web-deployment.rst
> -OMERO.web requires ``body_in_file_only`` adjusted in your default nginx
http://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_in_file_only ?

2017-08-24 14:34 UTC, joshmoore approved these changes

2017-08-24 14:41 UTC, manics commented on omero/sysadmins/unix/install-web/web-deployment.rst
> -OMERO.web requires ``body_in_file_only`` adjusted in your default nginx
I meant I can't find any mention of what it should be set to or why it's needed in our code or docs, nor any mention of it in our infrastructure repos.

2017-08-24 14:47 UTC, joshmoore commented on omero/sysadmins/unix/install-web/web-deployment.rst
> -OMERO.web requires ``body_in_file_only`` adjusted in your default nginx
Hmmm.... since 4f5cc2a0baa89cfab2b99f38a0c9c565e6c81a25 in gh-1244 -- I don't have anything else either.

2017-08-24 19:57 UTC, mtbc approved these changes
The prose parts look fine to me.

2017-08-25 08:08 UTC, jburel commented
Merging so I can continue with the web doc re-organisation

2017-08-25 08:08 UTC, merged