Add contributing page codifying C++ components development
openmicroscopy/ome-documentation pull request #1819
Opened 2017-12-05 10:50 UTC by sbesson

See https://trello.com/c/8l4Rgg6a/547-codify-c-components-development-process

Following the [release of OME Files](https://www.openmicroscopy.org/2017/12/04/ome-files-0-5-0.html), this page documents the current guidelines for the C++ repositories including
source control management, build system and development lifecycle.

2017-12-05 11:12 UTC, sbesson commented
NB: the last section i.e. bumping the release to the next patch number immediately after release has not been enforced so far. As this was discussed as part of the OME Files 0.5.0 release process and might be our best solution so far (see also https://gitlab.kitware.com/cmake/cmake/issues/16716), let us agree on the current statu quo and review it when needed.

2017-12-05 11:17 UTC, joshmoore commented
No objections to anything pushed to this state (i.e. 2554acfcb5d2f650d1f7c834eac2c1f6971d6ed1) but of course, in releasing, I didn't few if any of the mentioned steps myself.

2017-12-06 07:29 UTC, mtbc commented on contributing/cpp-development.rst
> +sources according to the Maven recommended layout i.e.::
Maven-recommended

2017-12-06 14:05 UTC, rleigh-codelibre commented
Looks fine to me.  Does ome-files-py need adding to the component list?

2017-12-19 12:25 UTC, manics requested changes

2017-12-19 12:25 UTC, manics commented on contributing/cpp-development.rst
> +[ome-common-cpp](https://github.com/ome/ome-common-cpp) use a flattened
The link is incorrectly formatted:

<img width="869" alt="screen shot 2017-12-19 at 10 03 03" src="https://user-images.githubusercontent.com/1644105/34151646-dce95e5a-e4a3-11e7-8c1d-965a4e74211c.png">

2017-12-19 12:25 UTC, manics commented on contributing/cpp-development.rst
> +[ome-model](https://github.com/ome/ome-model) organize the C++
Incorrect link formatting

2017-12-19 12:25 UTC, manics commented on contributing/cpp-development.rst
> +     sphinx/
There's no `sphinx` directory in https://github.com/ome/ome-common-cpp

2017-12-19 12:25 UTC, manics commented on contributing/cpp-development.rst
> +   src/main/java            Contains the Java code
I can't see these directories in https://github.com/ome/ome-model

2017-12-19 12:25 UTC, manics commented on contributing/cpp-development.rst
> +repository::
What happens after you create the archive? Is it created locally? Should it be copied somewhere?

2017-12-19 12:25 UTC, manics commented on contributing/cpp-development.rst
> +`x.y.z+1` and a suffixed with an `# unreleased` comment. If a top-level
`x.y.z+1` looks like it should be formatted as code/monospace but it's not:
<img width="87" alt="screen shot 2017-12-19 at 12 21 37" src="https://user-images.githubusercontent.com/1644105/34156919-31b6ba00-e4b7-11e7-9e19-60b21f5179ce.png">
Same for `# unreleased`

2017-12-19 12:25 UTC, manics commented on contributing/cpp-development.rst
> +- have a GitHub_ account and have push rights to the GitHub source code
I don't think it's necessary to hyperlink GitHub again- it gives the impression that clicking on it will lead to a relevant github resource

2017-12-19 12:25 UTC, manics commented on contributing/cpp-development.rst
> +from the Git_ repository.
I don't think it's necessary to hyperlink Git again- it gives the impression that clicking on it will lead to a relevant git resource

2017-12-20 08:39 UTC, sbesson commented
@manics pushed 3 commits which should address all your comments.

2018-01-04 14:17 UTC, hflynn commented
@manics is this good to merge now?

2018-01-15 13:51 UTC, joshmoore commented
Re-added to standup for @manics comment.

2018-01-16 09:54 UTC, rleigh-codelibre commented on contributing/cpp-development.rst
> +
Extra newline could be removed?

2018-01-16 09:58 UTC, rleigh-codelibre commented
One trivial formatting thing (which can be freely ignored) noted.  Looks fine to merge to me.

2018-01-16 10:13 UTC, rleigh-codelibre commented
Thanks, all looks good to merge.

2018-01-16 10:15 UTC, merged