Handle GH redirects from help to docs
openmicroscopy/ome-documentation pull request #2223
Opened 2022-04-12 08:45 UTC by joshmoore

see: https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-docs/1186/console

```
01:06:13 (developers/scripts/index: line   74) broken    https://help.github.com/articles/set-up-git - 403 Client Error: Forbidden for url: https://docs.github.com/articles/set-up-git
01:06:13 (developers/Web/CreateApp: line  135) broken    https://help.github.com/en/articles/creating-a-repository-from-a-template - 403 Client Error: Forbidden for url: https://docs.github.com/en/articles/creating-a-repository-from-a-template
01:06:13 (           index: line   51) broken    https://help.github.com/articles/about-pull-requests/ - 403 Client Error: Forbidden for url: https://docs.github.com/articles/about-pull-requests/
```

2022-04-13 08:15 UTC, sbesson requested changes
Still raises 403 when accessing it outside a browser - see https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-docs/1187. The linkcheck failures can be reproduced locally e.g. by issuing `curl -IL https://docs.github.com/articles/about-pull-requests/`.

I suspect we'll need either to use the equivalent deeper links or find landing pages like https://docs.github.com/en/pull-requests/ that link to the relevant content

2022-04-14 10:42 UTC, joshmoore commented
Wow. Some of those got _substantially_ longer.

2022-04-18 20:36 UTC, sbesson approved these changes

2022-04-19 05:06 UTC, joshmoore commented
😢

2022-04-19 05:06 UTC, merged