Add name and description opts, add link to it from limitations
openmicroscopy/ome-documentation pull request #2251
Opened 2022-06-27 15:43 UTC by pwalczysko

see https://github.com/ome/omero-documentation/issues/2249 for background.

Adds -n and -x options.

@sbesson Also added one example of usage. To be honest, I was confused myself, cf. paragraph "java options" of the same doc which seems to be asking for two double-dashes. Nevertheless, tested the example which I added as well as the variants -n and --name and -x and --description, all works.

2022-06-27 21:06 UTC, sbesson reviewed
The double dash is used to separate the arguments passed to the underlying Java command-line importer i.e. `omero import -- --java_arg_1 value_1 --java_arg_2 value_2`

The confusion stems from the fact the name and description arguments are defined both at the Python and at the Java level. I agree the Python form (without the double dash) should be preferred in the documentation.

One suggestion about splitting the addition into two separate blocks. Otherwise, looks great

2022-06-27 21:06 UTC, sbesson commented on omero/users/cli/import.rst
> +        $ omero import image.tif --name "Control image1" --description "PBS Control" -T Dataset:name:Controls
Since name and description are othogonal to the target containers, I originally thought of splitting them into their own option sections, what do you think?

2022-06-28 10:09 UTC, pwalczysko commented
@sbesson fixes pushed, also fixed some older remnants of imprecisely added blocks in https://github.com/ome/omero-documentation/pull/2251/commits/816256f26e3407e1f91e776e3cbf2f5722f41ac4

2022-06-28 10:13 UTC, sbesson requested changes
Looks good. One duplicated option to remove and then it should be ready to merge

2022-06-28 10:13 UTC, sbesson commented on omero/users/cli/import.rst
> +.. option:: --logprefix [LOGPREFIX]
Interestingly `--logprefix` is defined 3 options below so this can be simply removed.

2022-06-28 10:14 UTC, pwalczysko commented on omero/users/cli/import.rst
> +.. option:: --logprefix [LOGPREFIX]
HAH. Great, so this one was defined **only** three times :)

2022-06-28 10:18 UTC, pwalczysko commented
Fix pushed

2022-06-28 10:32 UTC, sbesson approved these changes

2022-06-28 10:32 UTC, merged