add mailmap
openmicroscopy/ome-documentation pull request #2349
Opened 2023-09-30 10:46 UTC by jburel

Add mailmap

3 entries that I cannot find info for 
* Steve Ogg (I can't find his current address)
* Felix cc (I remember felix but cannot remember his name)
* AarghIMApiratez ??
cc @joshmoore @sbesson 

This should allow to fix the entry in cla-audit

2023-10-03 14:33 UTC, sbesson requested changes
One suggestion. Reads fine otherwise

2023-10-03 14:33 UTC, sbesson commented on .mailmap
> +Simone Leo <s.z.leo@dundee.ac.uk> <simleo@crs4.it>
```suggestion
Simone Leo <s.z.leo@dundee.ac.uk> <simleo@crs4.it>
Tom Boissonnet <tom.boissonnet@hhu.de> <tom.boissonnet@hotmail.fr>
```

2023-10-03 14:53 UTC, sbesson approved these changes

2023-10-04 08:25 UTC, merged

2023-10-04 14:43 UTC, joshmoore commented
* For Steve, I currently have a kaust.edu.sa address
* For Felix, do you mean Meyenhofer?
* The pirate is apparently `Staffan_Holmqvist`

2023-10-04 14:48 UTC, jburel commented
* do you have steve.ogg at ...?
* Felix yes
* For Staffan_Holmqvist do you have contact info? I don't